apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eci-prometheus-exporter
  labels:
    app.kubernetes.io/name: eci-prometheus-exporter
spec:
  selector:
    matchLabels:
      app: eci-exporter
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s

