version: "2"
linters:
  default: all

  disable:
    - varnamelen
    - exhaustruct
    - wsl

  enable:
    - wsl_v5

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    ireturn: 
      allow:
        - anon
        - "error"
    depguard:
      rules:
        tests:
          files:
            - '$test'
          allow:
            - $gostd
            - go.uber.org/zap
            - github.com/stretchr/testify/assert
            - github.com/tvanriel/eci-prometheus-exporter
        main:
          files:
            - "$all"
            - "!$test"
          allow:
            - $gostd
            - go.uber.org/zap
            - github.com/prometheus/client_golang/prometheus
