profile: cover.out

threshold:
  file: 70
  package: 80
  total: 0

exclude:
  paths:
    - main.go$ # testing main is ridiculous.
    - threshold.go$ # don't really care so much.  Copypasted code from the ECI webportal.
