{
 "title": "ECI Initiatives",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "initiative_id",
    "label": "Initiative ID",
    "query": {
     "query": "label_values(eci_signatures,initiative_id)"
    }
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ![](https://citizens-initiative.europa.eu/themes/contrib/oe_theme/dist/eu/images/logo/standard-version/positive/logo-eu--en.svg)\n# European Citizens Initiative Tracker\n"
   }
  },
  {
   "title": "Countries where threshold was reached",
   "type": "stat",
   "description": "Shows the amount of countries where the signature threshold was reached",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( eci_signatures{initiative_id=\"$initiative_id\"} / eci_signature_threshold{initiative_id=\"$initiative_id\"} >= 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature percentage of threshold per country",
   "type": "timeseries",
   "description": "shows the percentage of the threshold that was reached per country.",
   "gridPos": { "h": 13, "w": 12, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( eci_signatures{initiative_id=\"$initiative_id\"} / eci_signature_threshold{initiative_id=\"$initiative_id\"} )",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Signature contribution per country",
   "type": "piechart",
   "description": "Shows the amount of signatures a country has contributed to the total. ",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eci_signatures{initiative_id=\"$initiative_id\"}",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Countries under threshold",
   "type": "stat",
   "description": "Shows the amount of countries where the signature threshold was reached",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( eci_signatures{initiative_id=\"$initiative_id\"} / eci_signature_threshold{initiative_id=\"$initiative_id\"} < 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closest country to threshold",
   "type": "stat",
   "description": "Shows the next country to reach threshold",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,\n  eci_signatures{initiative_id=\"$initiative_id\"}\n    / on(initiative_id, country_code)\n      eci_signature_threshold{initiative_id=\"$initiative_id\"}\n  and\n  eci_signatures{initiative_id=\"$initiative_id\"} < on(initiative_id, country_code) eci_signature_threshold{initiative_id=\"$initiative_id\"}\n)\n",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Signatures collected",
   "type": "timeseries",
   "description": "Shows the amount of signatures the initiative has collected along with their goal.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(eci_signatures{initiative_id=\"$initiative_id\"}) by(initiative_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signatures remaining",
   "type": "timeseries",
   "description": "Shows the amount of signatures that are yet to be collected before the goal has been reached.",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "clamp_min(\n  eci_signature_threshold{initiative_id=\"$initiative_id\"}\n    - on(initiative_id, country_code)\n      eci_signatures{initiative_id=\"$initiative_id\"},\n  0\n)",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Total signatures remaining ",
   "type": "timeseries",
   "description": "Shows the amount of signatures that are yet to be collected before the 1 000 000 signatures is reached.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "clamp_min(1000000 - sum(eci_signatures{initiative_id=\"$initiative_id\"}) by(initiative_id), 0)",
     "legendFormat": "{{initiative_id}}"
    }
   ]
  },
  {
   "title": "Signature Rate in countries don't reach threshold",
   "type": "barchart",
   "description": "Shows the rate of signature collection in countries where the threshold is yet to be reached",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(eci_signatures{initiative_id=\"$initiative_id\"}[5m])\n  * on(initiative_id, country_code)\n    group_left()\n    (\n      (eci_signatures{initiative_id=\"$initiative_id\"} / on(initiative_id, country_code) eci_signature_threshold{initiative_id=\"$initiative_id\"})\n      < 1\n    )",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "ECI Initiative Signature Rate",
   "type": "barchart",
   "description": "Shows the rate of signature collection.",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(eci_signatures{initiative_id=\"$initiative_id\"}[$__interval])",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Log output of the exporter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{namespace=\"eci-prometheus-exporter\"} | json | initiative_id = \"$initiative_id\" or initiative_id = \"\""
    }
   ]
  },
  {
   "title": "API call speed",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(eci_api_duration_seconds_bucket{initiative_id=\"$initiative_id\"}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}