apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/deployment.yaml
- resources/podmonitor.yaml
- resources/ns.yaml
namespace: eci-prometheus-exporter
configMapGenerator:
- files:
  - dashboard.json=./configs/dashboard.json
  name: grafana-dashboard
  options:
    labels:
      grafana_dashboard: "1"
